# Generated by Django 5.2.15 on 2026-06-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_posts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-created_at'], 'verbose_name': 'کامنت', 'verbose_name_plural': 'کامنت ها '},
        ),
    ]
